# Generated by Django 2.2.5 on 2021-02-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
    ]
